name: ble_wifi_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  tm_wifi_connect:
    path: "plugins/tm_wifi_connect"

  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  flutter_bloc: ^9.1.1
  flutter_blue_plus: ^1.36.8
  nfc_manager: ^4.1.1
  nfc_manager_ndef: ^1.1.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.14.1
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.14.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/

flutter_gen:
  assets:
    enabled: true
